const clues = [
  "Nombre afectivo y artístico del creador del juego de mesa <b>Jack Rabbits</b>.",
  "Lo que es el tablero; piezas romboides y triángulares conectando hexágonos reales.",
  "Lo que seguirán los conejos en sus travesías para ir libremente de un hexágono a otro.",
  "Piezas en las que la travesía se detiene al visitar a la nobleza; inicias en la ciudadela.",
  "Fichas que representan a quienes juegan; elijes uno entre cuatro colores.",
  "Dos cartas que se retiran del mazo junto a las doce de la nobleza, formando la corte.",
  "Cartas de nobleza que adquieres en las plazas; hay cuatro (una por cada palo).",
  "Lo que haces con el resto de las cartas, antes de repartir las manos y crear la pila.",
  "Cantidad de cartas numéricas con las que incian las manos (la misma que zanahorias).",
  "Conjunto de doce cartas nobles y dos jokers que no se incluyen en la pila.",
  "Lo que haces con las cartas usadas al adquirir nobles o pagar por traslados.",
  "Cartas de nobleza que adquieres en los palacios (Q); hay cuatro (una por palo).",
  "Triángulos donde puedes comprar jokers, que son comodines para traslados.",
  "Fichas para marcar los hexágonos de nobles que adquieres; tienes tres de tu color.",
  "Palos de color carmín que simbolizan tu estatus social; copas.",
  "Traslados con jokers, que te permiten reclamar un viaje a caballo o en bote.",
  "Forma de las fichas que tienen dos caminos separados por ríos, montañas o bosques",
  "Tipo de cartas hay que traer a la ciudadela para ganar el juego; necesitas tres.",
  "Máximo de cartas que puedes tener en tu mano (descarta el excedente si te pasas).",
  "En los cruces del camino, estos venden viajes a caballo o bote (si colindan al mar).",
  "En las piezas romboides, si pagas por estos traslados, te cambias de camino.",
  "Suma mínima de palos (de su símbolo) que necesitas pagar para aquirir un noble.",
  "Palos de color dorado que simbolizan tu riqueza económica; oros.",
  "Fase final del turno; tomas una carta de la pila (a menos que salgas al destierro).",
  "Precio de la travesía por piezas romboides y triangulares usando caminos contínuos.",
  "Fuera del tablero; desde donde en tu próximo turno te moverás al subsuelo.",
  "Otro nombre para las cuevas triangulares que conectan al subsuelo.",
  "Hexágono irregular al que se entra y sale por las cuevas (o desde el destierro).",
  "Hexágono donde comienza y termina el juego al traer las cartas de tres nobles.",
  "Cubos que determinan los números de la lotería y el precio de los traslados; hay dos.",
  "Trucos en la travesía que te permiten viajar fuera de los caminos.",
  "Segunda fase del turno, donde tomas un camino de un hexágono a otro.",
  "Fase inicial del turno, donde lanzas los dados y puedes ganar una carta de la pila.",
  "Hexágonos en los que aquieres a los reyes.",
  "Palos de color cerceta que simbolizan tu conocimiento de la naturaleza; bastos.",
  "Cartas de nobleza que adquieres en las torres (K); hay cuatro (uno por cada palo).",
  "Triángulos donde puedes comprar traslados inmediatos a caballo o en bote.",
  "Triángulos para entrar y salir del subsuelo; o si pagas, te trasladas entre ellos.",
  "Palos de color índigo que simbolizan tu poder de ataque; espadas.",
  "Hexágonos en los que adquieres a las jotas.",
  "Hexágonos en los que adquieres a las reinas.",
  "Penúltima fase del turno, donde puedes comprar la carta del hexágono que visitas.",
];

const words = [
  "  LENINO",
  "EL REINO",
  "  CAMINOS",
  "HEXAGONOS",
  "CONEJOS",
  "JOKERS",
  "JOTAS",
  "  BARAJAS",
  "     TRES",
  " LA CORTE",
  " DESCARTAS",
  "    REINAS",
  "  TAVERNAS",
  "ZANAHORIAS",
  "CORAZONES",
  "COMODINES",
  "ROMBOIDES",
  "   NOBLES",
  "    NUEVE",
  "MERCADERES",
  "VERICUETOS",
  "  DIEZ",
  "  DIAMANTES",
  "INCREMENTO",
  "  GRATIS",
  "  DESTIERRO",
  "MADRIGUERAS",
  "  SUBSUELO",
  " CIUDADELA",
  "    DADOS",
  "TRASLADOS",
  "TRAVESIA",
  " LOTERIA",
  "   TORRES",
  "   TREBOLES",
  "    REYES",
  "   CRUCES",
  "   CUEVAS",
  "    PICAS",
  "   PLAZAS",
  "   PALACIOS",
  "ADQUISICION",
];

export { clues, words };