const clues = [
  "Nombre afectivo y artístico del creador del juego de mesa <b>Jack Rabbits</b>.",
  "Lo que representa el tablero; piezas romboides y triángulos con caminos que conectan hexágonos.",
  "Lo que transitan libremente los conejos para ir de un hexágono a otro.",
  "Piezas en las que se detienen a visitar a la nobleza; la ciudadela es la inicial.",
  "Fichas que representan a quienes juegan; elijes uno entre cuatro colores.",
  "Dos cartas que se retiran del mazo junto a las doce de la nobleza forma la corte.",
  "Cartas de nobleza que adquieres en las plazas; hay cuatro (una por cada palo).",
  "Lo que haces con el resto de las cartas, antes de repartir las manos y crear la pila.",
  "Cartas numéricas que puedes decidir si valen por uno o por once a la hora de jugar.",
  "Cantidad de cartas numéricas con las que incian las manos (la misma que zanahorias).",
  "Conjunto de doce cartas nobles y dos jokers que se excluyen de la pila.",
  "Lo que haces con las cartas que usas para adquirir nobles o pagar traslados.",
  "Triángulos donde puedes comprar jokers, que son comodines para trasladarte.",
  "Cartas nobles que adquieres en los palacios (Q); hay cuatro (una por cada palo).",
  "Fichas para marcar los hexágonos de nobles que adquieres; tienes tres de tu color.",
  "Palos de color carmín que simbolizan tu nobleza, encanto o estatus social; copas.",
  "Traslados con jokers, que te permiten reclamar un viaje a caballo o en bote.",
  "Forma de las fichas que tienen dos caminos separados por un río, montaña o bosque",
  "Tipo de cartas a traer a la ciudadela para ganar el juego; necesitas tres.",
  "Máximo de cartas que puedes tener en tu mano (descarta el excedente si te pasas).",
  "En las piezas romboides, si pagas por estos traslados, te cambias de camino.",
  "En los cruces, estos te venden traslados a caballo o en bote (si colindan al mar).",
  "Piezas que son cuevas al subsuelo, tavernas de jokers or cruces con mercaderes.",
  "Lo que haces con los dados para determinar los números de la lotería y el precio de los tralados.",
  "Suma mínima de palos (de su símbolo) que necesitas pagar para aquirir un noble.",
  "Tipo de trío final de cartas nobles en donde cada una pertenece a distintos palos.",
  "Palos de color dorado que simbolizan tu riqueza económica; oros.",
  "Fase final del turno; tomas una carta de la pila (a menos que salgas al destierro).",
  "Precio de la travesía por piezas romboides y triangulares usando caminos contínuos.",
  "Fuera del tablero; desde donde en tu próximo turno te moverás al subsuelo.",
  "Otro nombre para las cuevas triangulares que conectan al subsuelo.",
  "Hexágono irregular al que se entra y sale por las cuevas (o desde el destierro).",
  "Hexágono donde comienza y termina el juego al traer las cartas de tres nobles.",
  "Lo que lanzas para determinar los números de la lotería y el precio de los traslados; hay dos.",
  "Trucos en la travesía que te permiten viajar fuera de los caminos.",
  "Segunda fase del turno, donde tomas un camino de un hexágono a otro.",
  "Sistema de valores donde el rey vale más que la reina y ambos mas que las jotas.",
  "Tipo de trío final de cartas nobles, donde todas tienen el mismo palo.",
  "Fase inicial del turno, donde lanzas los dados y puedes ganar una carta de la pila.",
  "Palos de color cerceta que simbolizan tu conocimiento de la naturaleza; bastos.",
  "Hexágonos en los que aquieres a los reyes.",
  "Cartas de nobleza que adquieres en las torres (K); hay cuatro (uno por cada palo).",
  "Triángulos con mercaderes que vended traslados inmediatos a caballo o en bote.",
  "Triángulos para entrar y salir del subsuelo; o pagas y te trasladas entre ellos.",
  "Palos de color índigo que simbolizan tu poder de ataque; espadas.",
  "Hexágonos en los que adquieres a las jotas.",
  "Hexágonos en los que adquieres a las reinas.",
  "Penúltima fase del turno, donde puedes comprar la carta del hexágono que visitas.",
  "Tipo de trío final de cartas nobles compuesto de rey, reina y jota.",
  "Valor que les puedes asignar a los ases a parte de uno.",
];

const words = [
  "   LENINO",
  " EL REINO",
  "   CAMINOS",
  " HEXAGONOS",
  " CONEJOS",
  "  JOKERS",
  "  JOTAS",
  "  BARAJAS",
  "       ASES",
  "       TRES",
  "  LA CORTE",
  "  DESCARTAS",
  "   TAVERNAS",
  "     REINAS",
  " ZANAHORIAS",
  " CORAZONES",
  " COMODINES",
  " ROMBOIDES",
  "    NOBLES",
  "    NUEVE",
  "VERICUETOS",
  "MERCADERES",
  " TRIANGULOS",
  "   LANZAS",
  "  DIEZ",
  "  DIVERSO",
  "  DIAMANTES",
  "INCREMENTO",
  "  GRATIS",
  "  DESTIERRO",
  "MADRIGUERAS",
  "  SUBSUELO",
  " CIUDADELA",
  "    DADOS",
  "TRASLADOS",
  "   TRAVESIA",
  " PATRIARCAL",
  "     TRIBAL",
  "  LOTERIA",
  "   TREBOLES",
  " TORRES",
  "  REYES",
  " CRUCES",
  " CUEVAS",
  "  PICAS",
  "  PLAZAS",
  "   PALACIOS",
  "ADQUISICION",
  " MONARQUICO",
  "  ONCE",
];

export { clues, words };