const clues = [
  "Nombre afectivo y artístico del creador del juego de mesa <b>Jack Rabbits</b>.",
  "Territorio monárquico; tablero, piezas romboides y triángulos con caminos conectando hexágonos.",
  "Meta, objetivo; en este caso, adquirir tres cartas nobles y traerlas a la ciudadela.",
  "Rutas, vías; por donde los conejos viajan libremente de hexágono a hexágono.",
  "Figuras geométricas; piezas en las que hay que detenerse; la ciudadela es la inicial.",
  "Roedores orejones; fichas que representan quienes juegan (elijen uno entre cuatro colores).",
  "Jacks; cuatro cartas nobles que se adquieren en las plazas; hay una por cada palo.",
  "Comodines; dos cartas exclusivas que junto a las doce nobles forman la corte y se retiran del mazo.",
  "Revuelves, mezclas el mazo de cartas; lo haces antes de repartir tres por participantes y crear la pila.",
  "Naipes, barajas; necesitas tres nobles para ganar al regresar a la ciudadela.",
  "La aristocracia, la nobleza; doce cartas nobles y dos jokers que se separan de la pila.",
  "Desechas, eliminas; gastas cartas en la adquisición de nobles o pago de traslados.",
  "Bienes, fortuna; grupo diverso de cartas numerales en tu mano (picas, corazones, diamantes y tréboles).",
  "Cantidad inicial de cartas en manos, de zanahorias individuales, y de nobles necesarios para ganar.",
  "Campeones, primeros; cartas numerales que decides si valen uno u once al jugarlas (A).",
  "Cantinas, tiendas; triángulos donde puedes comprar jokers comodines para tus traslados.",
  "Damas, soberanas; cuatro cartas nobles que se adquieren en los palacios (Q); queens.",
  "Raíces comestibles; tres fichas del color de tu conejo para marcar los hexágonos de tus nobles.",
  "Palos de color carmín que simbolizan nobleza, encanto o estatus social; copas.",
  "Acomodadines, despreocupadines; jokers que descartas para reclamar un viaje (caballo o bote).",
  "Cuadrilaterales, adiamantadas; formas de piezas con dos caminos y vericuetos entre ellos.",
  "Reales, aristocratas; cartas de las que tienes que traer tres a la ciudadela para ganar.",
  "Número máximo de cartas que dedes llegar a tener en mano (descartas el excedente).",
  "Atajos, senderos; traslados que pagas para cruzar de un camino al otro en piezas las romboides.",
  "Comerciantes; vendedores en los cruces que ofrecen traslados inmediatos a caballo o en bote.",
  "Numéricas; cartas con recursos que descartas en la adquisicion de nobles y traslados.",
  "Figuras geométricas; piezas con cuevas al subsuelo, tabernas de jokers, o cruces de mercaderes.",
  "Picas, garrochas; o acción inicial del turno: tiras dados que fijan la lotería y el precio de los traslados.",
  "Valor numérico de una carta noble; suma mínima de palos de su símbolo necesaria para aquirirla.",
  "Variado, distinto; fin del juego con tres cartas nobles de palos diferentes.",
  "Joyas, gemas; palos dorados que simbolizan riqueza económica; oros.",
  "Aumento, suma; fase final del turno donde tomas una carta de la pila (si no sales al destierro).",
  "Expulsión, salida; fuera del tablero, desde donde irás al subsuelo en tu próximo turno.",
  "Gratuito; precio de la travesía si cruzas las piezas usando los caminos.",
  "Guaridas, escondrijos; triángulos con cuevas que llevan los conejos al subsuelo.",
  "Subterráneo, madriguera; hexágono irregular al que llegas por las cuevas o por destierro.",
  "Castillo, fortaleza; hexágono donde comienza y termina el juego al traer tres cartas nobles.",
  "Cubos; los dos que lanzas para fijar los números de la lotería y el precio de los traslados.",
  "Traspasos, transportes; trucos en la travesía para viajar por fuera de los caminos.",
  "Viaje, recorrido; segunda fase del turno donde tomas un camino de un hexágono a otro.",
  "Ancestral, misógino; sistema donde los reyes valen más que las reinas y estos más que las jotas.",
  "Primitivo, familiar; fin del juego con tres cartas nobles del mismo palo.",
  "Azar, rifa; fase inicial del turno donde lanzas dados y puedes ganar una carta de la pila.",
  "Hojas, trifolios; palos color cerceta que simbolizan el conocimiento natural; bastos.",
  "Torreones, atalayas; hexágonos en los que se aquieren los reyes.",
  "Señores, monarcas; cuatro cartas nobles que se adquieren en las torres (K).",
  "Encrucijadas; triángulos con mercaderes que venden traslados inmediatos a caballo o bote.",
  "Cavernas, madrigueras; triángulos de acceso al subsuelo y con traslados inmediatos entre ellos.",
  "Flechas, lanzas tipo tribal; palos de color índigo que simbolizan el poder bélico; espadas.",
  "Plazoletas, mercados; hexágonos en los que se adquieren las jotas.",
  "Mansiones, palacetes; hexágonos en los que se adquieren las reinas.",
  "Compra, obtención; fase del turno antes del incremento, donde puedes adquirir el noble que visitas.",
  "Dinástico, principesco; fin del juego donde las cartas nobles son un rey, una reina y una jota.",
  "Undécimo; valor que le puedes asignar a los ases a parte de uno.",
];

const words = [
  "   LENINO",
  "    REINO",
  "     MISION",
  "   CAMINOS",
  " HEXAGONOS",
  "   CONEJOS",
  "   JOTAS",
  "   JOKERS",
  "  BARAJAS",
  "   CARTAS",
  "LA CORTE",
  "DESCARTAS",
  " RECURSOS",
  "    TRES",
  "    ASES",
  "   TABERNAS",
  "     REINAS",
  " ZANAHORIAS",
  " CORAZONES",
  " COMODINES",
  " ROMBOIDES",
  "    NOBLES",
  "    NUEVE",
  "VERICUETOS",
  "MERCADERES",
  "  NUMERALES",
  " TRIANGULOS",
  "   LANZAS",
  "   DIEZ",
  "  DIVERSO",
  "  DIAMANTES",
  "INCREMENTO",
  " DESTIERRO",
  " GRATIS",
  "MADRIGUERAS",
  "  SUBSUELO",
  " CIUDADELA",
  "    DADOS",
  "TRASLADOS",
  "   TRAVESIA",
  " PATRIARCAL",
  "     TRIBAL",
  "  LOTERIA",
  "   TREBOLES",
  "     TORRES",
  "      REYES",
  "   CRUCES",
  "    CUEVAS",
  "   PICAS",
  "  PLAZAS",
  "   PALACIOS",
  "ADQUISICION",
  " MONARQUICO",
  "  ONCE",
];

export { clues, words };
