const clues = [
  "Nombre afectivo y artístico del creador del juego de mesa <b>Jack Rabbits</b>.",
  "El territorio monárquico; piezas romboides y triángulos con caminos que conectan los hexágonos.",
  "La meta, el objetivo; adquirir tres cartas nobles y traerlas a la ciudadela.",
  "Rutas, vías; por donde los conejos se mueven libremente entre hexágonos.",
  "Figuras geométricas; piezas en las que hay que detenerse; la ciudadela es la inicial.",
  "Roedores orejones; fichas que representan a quien juega; elije uno entre cuatro.",
  "Jacks; cartas nobles que se adquieren en plazas; hay cuatro (una por palo).",
  "Comodines; dos cartas exclusivas que junto a las doce nobles forman la corte; retíralas del mazo.",
  "Revuelves; mezclas el resto de las cartas, para repartir tres por participante y crear la pila.",
  "Naipes, barajas; necesitas tres nobles para ganar al volver a la ciudadela.",
  "La aristocracia, la nobleza; doce cartas nobles y dos jokers que se excluyen de la pila.",
  "Desechas, eliminas; gastas tus cartas en la adquisición de nobles y pago de traslados.",
  "Bienes, fortuna; grupo diverso de cartas en tu mano (picas, corazones, diamantes y tréboles).",
  "Cantidad inicial de cartas en las manos, o de zanahorias, o de nobles necesarios para ganar.",
  "Campeones, primeras; cartas numerales que decides si valen uno u once al jugar.",
  "Cantinas, posadas; triángulos donde puedes comprar jokers o comodines para traslados.",
  "Damas, soberanas; cuatro cartas nobles que se adquieren en palacios (Q); queens.",
  "Hortalizas, raíces; tres fichas de tu color para marcar los hexágonos de tus nobles.",
  "Palos de color carmín que simbolizan nobleza, encanto o estatus social; copas.",
  "Diminutivo de cómodo (pl.); jokers para reclamar un viaje a caballo o en bote.",
  "Cuadrilaterales; piezas con dos caminos y vericuetos entre ríos, montañas o bosques",
  "Reales, aristocratas; cartas a traer a la ciudadela para ganar (necesitas tres).",
  "Número máximo de cartas que puedes tener en tu mano (descarta el excedente).",
  "Atajos, senderos; los pagas para trasladarte de un camino al otro en piezas romboides.",
  "Comerciantes, vendedores en los cruces; venden traslados a caballo o en bote.",
  "Numéricas; cartas de recursos que descartas para adquirir nobles o traslados.",
  "Figuras geométricas; piezas con cuevas al subsuelo, tabernas de jokers, o cruces de mercaderes.",
  "Picas, garrochas; tiras los dados para fijar los números de la lotería y el precio de los traslados.",
  "Decena; suma mínima de palos de su símbolo necesaria para aquirir un noble.",
  "Variado, distinto; final donde las tres cartas nobles tienen palos diferentes.",
  "Joyas, gemas; palos dorados que simbolizan riqueza económica; oros.",
  "Aumento, suma; fase final del turno donde tomas una carta de la pila si no sales al destierro.",
  "Expulsión, salida; fuera del tablero, desde donde en tu próximo turno irás al subsuelo.",
  "Gratuito; precio de la travesía si cruzas las piezas usando sus caminos.",
  "Guaridas, escondrijos; cuevas triangulares que llevan los conejos al subsuelo.",
  "Subterráneo, madriguera; hexágono irregular al que llegas por cuevas o del destierro.",
  "Castillo, fortaleza; hexágono donde comienza y termina el juego al traer tres cartas nobles.",
  "Cubos; lanzas dos para fijar los números de la lotería y el precio de los traslados.",
  "Traspasos, transportes; trucos en la travesía para salir fuera de los caminos.",
  "Viaje, recorrido; segunda fase del turno donde tomas un camino de un hexágono a otro.",
  "Ancestral, misógino; sistema donde los reyes valen más que las reinas y ambos más que las jotas.",
  "Primitivo, familiar; tipo de final donde las tres cartas nobles tienen el mismo palo.",
  "Azar, rifa; fase inicial del turno donde lanzas los dados y puedes ganar una carta de la pila.",
  "Hojas, trifolios; palos color cerceta que simbolizan el conocimiento natural; bastos.",
  "Torreones, atalayas; hexágonos en los que aquieres a los reyes; kings.",
  "Señores, monarcas; cuatro cartas nobles que se adquieren en las torres (K).",
  "Encrucijadas, encuentros; triángulos con mercaderes (traslados inmediatos a caballo o en bote).",
  "Cavernas, madrigueras; triángulos para acceder al subsuelo o pagar por traslados entre ellos.",
  "Flechas, lanzas tipo tribal; palos índigos que simbolizan el poder de ataque; espadas.",
  "Plazoletas, mercados; hexágonos en los que se adquieren las jotas.",
  "Mansiones, palacetes; hexágonos en los que se adquieren las reinas.",
  "Compra, obtención; fase antes del incremento, donde puedes pagar por la carta del hexágono que visitas.",
  "Dinástico, principesco; final donde las cartas nobles son un rey, una reina y una jota.",
  "Undécimo; valor que les puedes asignar a los ases a parte de uno.",
];

const words = [
  "   LENINO",
  " EL REINO",
  "  LA MISION",
  "   CAMINOS",
  " HEXAGONOS",
  "   CONEJOS",
  "   JOTAS",
  "   JOKERS",
  "  BARAJAS",
  "   CARTAS",
  "LA CORTE",
  "DESCARTAS",
  " RECURSOS",
  "    TRES",
  "    ASES",
  "   TABERNAS",
  "     REINAS",
  " ZANAHORIAS",
  " CORAZONES",
  " COMODINES",
  " ROMBOIDES",
  "    NOBLES",
  "    NUEVE",
  "VERICUETOS",
  "MERCADERES",
  "  NUMERALES",
  " TRIANGULOS",
  "   LANZAS",
  "   DIEZ",
  "  DIVERSO",
  "  DIAMANTES",
  "INCREMENTO",
  " DESTIERRO",
  " GRATIS",
  "MADRIGUERAS",
  "  SUBSUELO",
  " CIUDADELA",
  "    DADOS",
  "TRASLADOS",
  "   TRAVESIA",
  " PATRIARCAL",
  "     TRIBAL",
  "  LOTERIA",
  "   TREBOLES",
  "     TORRES",
  "      REYES",
  "   CRUCES",
  "    CUEVAS",
  "   PICAS",
  "  PLAZAS",
  "   PALACIOS",
  "ADQUISICION",
  " MONARQUICO",
  "  ONCE",
];

export { clues, words };
