const clues = [
  "Nombre afectivo y artístico del creador del juego de mesa <b>Jack Rabbits</b>.",
  "Lo que representa el tablero; piezas romboides y triángulos con caminos que conectan los hexágonos.",
  "El objetivo; en este caso, adquirir tres cartas nobles y traerlas a la ciudadela.",
  "Sirven para que los conejos se muevan libremente entre hexágonos.",
  "Piezas en las que hay que detenerse al llegar; la ciudadela es la inicial.",
  "Fichas que representan a quienes juegan; elijes uno entre cuatro colores.",
  "Ejemplo de cartas nobles que se adquieren en plazas; de estas hay cuatro (una por palo).",
  "Dos cartas exclusivas que junto a las doce de la nobleza forman la corte (la cual se retira del mazo).",
  "Lo que haces con el resto de las cartas, para repartir tres por participante y crear la pila.",
  "Sinónimo de la palabra anterior, que compone el mazo; necesitas tres nobles para ganar.",
  "Conjunto de doce cartas nobles y dos jokers que se excluyen de la pila.",
  "Lo que haces con las cartas que gastas en la adquisición de nobles o pagando traslados.",
  "Lo que representan las cartas en tu mano (picas, corazones, diamantes y tréboles).",
  "Cantidad inicial de cartas en las manos (misma que zanahorias y  nobles necesarios para ganar).",
  "Cartas numerales que puedes decidir si valen uno u once a la hora de jugar.",
  "Triángulos donde puedes comprar jokers, que son comodines para trasladarte.",
  "Otras cartas nobles; estas se adquieren en palacios (Q); hay cuatro (una por palo).",
  "Fichas para marcar los hexágonos de nobles que adquieres; tienes tres de tu color.",
  "Palos de color carmín que simbolizan tu nobleza, encanto o estatus social; copas.",
  "Traslados con jokers, que te permiten reclamar un viaje a caballo o en bote.",
  "Piezas que muestran dos caminos separados por vericuetos entre ríos, montañas o bosques",
  "Tipo de cartas a traer a la ciudadela para ganar el juego; necesitas tres.",
  "Máximo de cartas que puedes tener en tu mano (descarta el excedente si te pasas).",
  "En las piezas romboides, si pagas por estos traslados, te cambias de un camino al otro.",
  "En los cruces, estos te venden traslados a caballo o en bote (si colindan al mar).",
  "Cartas que son los recursos que descartas para adquirir nobles o traslados.",
  "Piezas que son cuevas al subsuelo, o tavernas de jokers, o cruces con mercaderes.",
  "Lo que haces con los dados para determinar los números de la lotería y el precio de los traslados.",
  "Suma mínima de palos (de su símbolo) que necesitas pagar para aquirir un noble.",
  "Tipo de final donde las tres cartas nobles tienen palos distintos.",
  "Palos de color dorado que simbolizan tu riqueza económica; oros.",
  "Fase final del turno, donde tomas una carta de la pila (a menos que salgas al destierro).",
  "Fuera del tablero; desde donde en tu próximo turno te moverás al subsuelo.",
  "Precio de la travesía si cruzas las piezas romboides y triangulares usando sus caminos.",
  "Otro nombre para las cuevas triangulares que conectan al subsuelo.",
  "Hexágono irregular al que se entra y sale por las cuevas (o desde el destierro).",
  "Hexágono donde comienza y termina el juego al traer las cartas de tres nobles.",
  "Lo que lanzas para determinar los números de la lotería y el precio de los traslados; hay dos.",
  "Trucos en la travesía que te permiten viajar fuera de los caminos.",
  "Segunda fase del turno, donde tomas un camino de un hexágono a otro.",
  "Sistema donde el rey vale más que la reina y ambos mas que las jotas.",
  "Tipo de final donde las tres cartas nobles tienen el mismo palo.",
  "Fase inicial del turno, donde lanzas los dados y puedes ganar una carta de la pila.",
  "Palos de color cerceta que simbolizan tu conocimiento de la naturaleza; bastos.",
  "Hexágonos en los que aquieres a los reyes.",
  "Cartas de nobleza que adquieres en sus torres (K); hay cuatro (uno por cada palo).",
  "Triángulos con mercaderes que venden traslados inmediatos a caballo o en bote.",
  "Triángulos para entrar y salir del subsuelo; o pagas y te trasladas entre ellos.",
  "Palos de color índigo que simbolizan tu poder de ataque; espadas.",
  "Hexágonos en los que adquieres a las jotas.",
  "Hexágonos en los que adquieres a las reinas.",
  "Fase del turno antes del incremento, donde puedes comprar la carta del hexágono que visitas.",
  "Tipo de final donde las tres cartas nobles son un rey, una reina y una jota.",
  "Valor que les puedes asignar a los ases a parte de uno.",
];

const words = [
  "   LENINO",
  " EL REINO",
  "  LA MISION",
  "   CAMINOS",
  " HEXAGONOS",
  "   CONEJOS",
  "   JOTAS",
  "   JOKERS",
  "  BARAJAS",
  "   CARTAS",
  "LA CORTE",
  "DESCARTAS",
  " RECURSOS",
  "    TRES",
  "    ASES",
  "   TAVERNAS",
  "     REINAS",
  " ZANAHORIAS",
  " CORAZONES",
  " COMODINES",
  " ROMBOIDES",
  "    NOBLES",
  "    NUEVE",
  "VERICUETOS",
  "MERCADERES",
  "  NUMERALES",
  " TRIANGULOS",
  "   LANZAS",
  "   DIEZ",
  "  DIVERSO",
  "  DIAMANTES",
  "INCREMENTO",
  " DESTIERRO",
  "     GRATIS",
  "MADRIGUERAS",
  "  SUBSUELO",
  " CIUDADELA",
  "    DADOS",
  "TRASLADOS",
  "   TRAVESIA",
  " PATRIARCAL",
  "     TRIBAL",
  "  LOTERIA",
  "   TREBOLES",
  "     TORRES",
  "      REYES",
  "   CRUCES",
  "    CUEVAS",
  "   PICAS",
  "  PLAZAS",
  "   PALACIOS",
  "ADQUISICION",
  " MONARQUICO",
  "  ONCE",
];

export { clues, words };
